### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Data33** [Liamso/V-Scheduler#5]
Hi!

I might be interested in using this in one of my work projects, but I couldn't find a license file anywhere.
Are you ok with businesses using this package? If so, might I suggest adding a `license.md` file or such stating which license to adhere to? :)

I'd gladly help you out with a PR if you just tell me which license you want

**Comment by Liamso** [comment]
Hey @Data33, 

Very glad to hear you might use the project! It's sat dormant for a little while now but if you come across things you'd desire or bugs, please let me know as you find them (or, even better, create a PR!). 

If you could create a PR with an MIT license which should allow you to use it for business applications that'd be great. Otherwise I'll find some time in the coming days to do so. I'd love to know what you end up using it for, if you do, on Discord - Liamso#6724

**Comment by Data33** [comment]
Sorry about the delay! I got caught up in another project at work for a bit.
I've submitted a PR #7  with the MIT license for you, hope I got it right :)

On a side note, we ended up forking your repo in private and modifying it to work with `dayjs` instead of `moment`.
If that's something you're looking to do, give me a shout and I'll PR that for you as well 👍

**Comment by Liamso** [comment]
Hey @Data33 , thanks a lot! I've merged in the request. I'd love to see your PR for dayjs - I hadn't heard of it until you mentioned it just now. As you can probably see one of the goals was to keep a small footprint with this package so it'll probably be perfect.
